language: php

php:
  - 5.3
  - 5.4

env:
  - DB=mysql

before_script:
  - pwd
  - composer install --dev
  - mysql -e "CREATE DATABASE IF NOT EXISTS todotestdb;" -uroot;
  - mysql -e "CREATE TABLE IF NOT EXISTS todotestdb.item (id int(11) NOT NULL AUTO_INCREMENT, name varchar(255) NOT NULL, created datetime NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;" -uroot;
  - mysql -e "INSERT INTO todotestdb.item VALUES (null, 'Download silex-skeleton-rest.', '2013-01-01 00:00:00'), (null, 'Utilize the skeleton so I can use it for my project.', '2013-01-06 19:00:00');" -uroot;

script: phpunit -c app/
